### ISSUE TITLE
Update Schema

### ISSUE THREAD

**Issue by maykelrodrigs** [katan/ionic-sql-service#1]
If I update the schema, what should I do?

In addition, it would be interesting to have a version handling for each schema change.

**Comment by katan** [comment]
Hi Maykel,
Depens of your implementation. The schema is load with the method "setSqlSchema" therefore at any moment you can change the schema.
If the new schema has a new table (for example) you must use a create query.

If your implementation has been launched at the first start to create the schema (like a welcome page) and you are debugging under Web SQL, you must be clear the storage on developer tools window. (over chrome browser)

I don't contemplate any implementation at this moment about version handling. Which is the reason to versioning schemas?

Best regards.
